services:
  backend:
    build: .devcontainer/backend
    volumes:
      - ./backend-src:/workspaces/backend-src/ 
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: /workspaces/backend-src/app.py
    ports:
      - 5000:5000
  # ...
  frontend:
    build: .devcontainer/frontend
    volumes:
      - ./frontend-src:/workspaces/frontend-src/  
    depends_on:
      - backend
  # ...
  db:
    image: mysql:8.0.39
    ports:
      - 9876:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'easy_diet_db'
    volumes:
      - sqldata:/var/lib/mysql
      - ./init-db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    
volumes:
  sqldata: