services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - ./backend-src:/workspaces/
  # ...
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ./frontend-src:/workspaces/
  # ...
  database:
    image: mysql:8.0
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql