services:
  backend:
    build: .devcontainer/backend
    volumes:
      - ./backend-src:/workspaces/backend-src/ 
    depends_on:
      - db
    command: sleep infinity
    ports:
      - 5001:5000
    # # command: ["flask db init", "flask db migrate -m 'Initial migration'","flask db upgrade"]
  # ...
  frontend:
    build: .devcontainer/frontend
    volumes:
      - ./frontend-src:/workspaces/frontend-src/  
    command: 'sleep infinity'
    depends_on:
      - backend
  # ...
  db:
    image: mysql:8.0.39
    ports:
      - 9876:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db_diet'
    volumes:
      - sqldata:/var/lib/mysql
      - ./init-db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
volumes:
  sqldata: